name: 'pm2使用nuxt自动部署'
description: '提交到服务器并使用pm2部署运行'
inputs:
  serverip:
    description: '服务端地址'
    required: true
  serveruser:
    description: '登录用户'
    required: true
  sshkey:
    description: '登录凭证'
    required: true
  source:
    description: '文件'
    required: true
  uploadremote:
    description: 'ftp目录'
    required: true
  target:
    description: '项目目录'
    required: true
runs:
  using: 'node12'
  main: 'index.js'